### ISSUE TITLE
fresh install, AttributeError: 'dict' object has no attribute 'get_changed'

### ISSUE THREAD

**Issue by ycardon** [gene-git/wg_tool#1] opened 2022-11-30 22:55 UTC
Hi, I'm very new to Wireguard,

Under Archlinux, I've installed `wireguard-tools` and `wg_tool` packages. Configured nothing and launched `wg-tool --init`. I then get the following python error. What do I miss?

```
> wg-tool --init
Init Mode
Making sample server config - please edit for your setup
Traceback (most recent call last):
  File "/usr/bin/wg-tool", line 26, in <module>
    main()
  File "/usr/bin/wg-tool", line 22, in main
    wgtool.doit()
  File "/usr/lib/python3.10/site-packages/wg_tool/lib/class_wg.py", line 308, in doit
    write_server_config(self)
  File "/usr/lib/python3.10/site-packages/wg_tool/lib/write_config.py", line 38, in write_server_config
    if wgtool.server.get_changed() :
AttributeError: 'dict' object has no attribute 'get_changed'
```

**Comment by gene-git** [comment] 2022-11-30 23:18
Thanks for letting me know - looks like I introduced a bug when adding new features - and my regression test didn't catch it.

I'll look into it and fix it as quickly as I can.

Thanks again

**Comment by gene-git** [comment] 2022-11-30 23:31
Fix will be uploaded shortly. Thank you for letting me know.

**Comment by gene-git** [comment] 2022-11-30 23:38
Fixed in version 3.6.0 (aur also updated) - let me know if you find otherwise.

Thanks again

**Closed by gene-git** 2022-11-30 23:38 UTC

**Comment by ycardon** [comment] 2022-12-01 06:47
Working great! Thank you for your reactivity.

**Comment by gene-git** [comment] 2022-12-01 11:07
Glad its working for you now. Have good day.
